version: '3.8'
services:
  db:
    image: postgres:15
    ports:
      - "6543:6543"
    environment:
      POSTGRES_PASSWORD: .xJc!2Z2dmU*9jU

  backend:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://aws-0-us-west-1.pooler.supabase.com:6543/postgres
      PG_DATABASE_URL: jdbc:postgresql://aws-0-us-west-1.pooler.supabase.com:6543/postgres
      SPRING_DATASOURCE_USERNAME: postgres.mwodaxqkcnidujjnabri
      SPRING_DATASOURCE_PASSWORD: .xJc!2Z2dmU*9jU

volumes:
  db-data: